name: CI

on:
  push:
      branches: [master]
  pull_request:
      branches: [master]

jobs:
  build:
    # FIXME: This builds with macOS 10.15. Move this to the 11.0 builders when possible. (See: https://github.com/actions/virtual-environments/issues/2486)
    runs-on:  macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          export CFLAGS="-mmacosx-version-min=10.13"
          xcodebuild -project iTerm2.xcodeproj -scheme iTerm2 CODE_SIGNING_ALLOWED=NO
          
      - name: compress
        if: always()
        run: |
          zip -r iTerm2.zip /Users/runner/Library/Developer/Xcode/DerivedData
          
      - name: Upload MacVim image
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: iTerm2.zip
          path: iTerm2.zip
